name: Build latest
on:
  schedule:
    - cron: '0 22 2 * *'
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Docker image
        uses: ./.github/actions/build/
        with:
          context: ./alpine/
          tags: |
            paperist/alpine-texlive-ja:latest
            ghcr.io/paperist/alpine-texlive-ja:latest
            paperist/texlive-ja:alpine
            ghcr.io/paperist/texlive-ja:alpine
