name: Build PR
on:
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build Docker image
        uses: ./.github/actions/build/
        with:
          context: ./alpine/
          load: true
          tags: |
            paperist/texlive-ja:alpine
      - name: Test
        run: |
          docker run --rm -v ${PWD}/tests:/workdir paperist/texlive-ja:alpine \
            sh -c 'latexmk -C main.tex && latexmk main.tex && latexmk -c main.tex';
      - name: Upload result
        uses: actions/upload-artifact@v2
        with:
          path: ./tests/main.pdf
