name: Build PR
on:
  pull_request:
    branches:
      - main
jobs:
  build-alpine:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
      - name: Build Docker image
        uses: ./.github/actions/build/
        with:
          context: ./alpine/
          load: true
          tags: |
            paperist/texlive-ja:alpine
      - name: Test
        run: |
          docker run --rm -v ${PWD}/tests:/workdir paperist/texlive-ja:alpine \
            sh -c 'latexmk -C main.tex && latexmk main.tex && latexmk -c main.tex';
      - name: Upload result
        uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4.3.3
        with:
          name: alpine
          path: ./tests/main.pdf
  build-debian:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
      - name: Build Docker image
        uses: ./.github/actions/build/
        with:
          context: ./debian/
          load: true
          tags: |
            paperist/texlive-ja:debian
      - name: Test
        run: |
          docker run --rm -v ${PWD}/tests:/workdir paperist/texlive-ja:debian \
            sh -c 'latexmk -C main.tex && latexmk main.tex && latexmk -c main.tex';
      - name: Upload result
        uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4.3.3
        with:
          name: debian
          path: ./tests/main.pdf
  build-debian-arm64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
      - name: Build Docker image
        uses: ./.github/actions/build/
        with:
          context: ./debian/
          platforms: linux/arm64
